plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'vidio'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// 트래픽, 대용량 전송을 위한 webflux 사용(RestTemplete은 Deprecated 예정)
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	// 개발 편의
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// 테스트
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// JavaCV (FFmpeg 포함)
	implementation 'org.bytedeco:javacv-platform:1.5.10'

	//FFmpeg4Java
	implementation files('libs/ffmpeg4java-0.8.0.jar')

	//FFmpegWrapper
	implementation 'net.bramp.ffmpeg:ffmpeg:0.8.0'
}

tasks.named('test') {
	useJUnitPlatform()
}
