spring.application.name=editor

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.file-size-threshold=1MB

ffmpeg.path=C:\\ffmpeg\\bin\\ffmpeg.exe
ffmpeg.ffprobe-path=C:\\ffmpeg\\bin\\ffprobe.exe
modelapi.url=http://127.0.0.1:8000
